const Routes = {
  Home: '/',
  SignIn: '/sign-in',
  SignUp: '/sign-up',
  Users: '/users',
  User: (id: string) => `/users/${id}`,
  UserEmail: '/users/email',
  Accounts: '/accounts',
  Account: (id: string) => `/accounts/${id}`,
  AccountProvider: '/accounts/provider',
  Posts: '/posts',
  Post: (id: string) => `/posts/${id}`,
  Cart: '/cart',
  Collection: '/collection',
  Books: '/books',
  Book: (id: string) => `/books/${id}`,
  Categories: '/categories',
  Category: (id: string) => `/categories/${id}`,
  Contact: '/contact',
  Profile: (id: string) => `/profile/${id}`,
  Tags: '/tags',
  Tag: (id: string) => `/tags/${id}`,
  SignInWithOAuth: '/auth/sign-in-with-oauth',
}

export default Routes
