import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import { SessionProvider } from 'next-auth/react'
import { ReactNode } from 'react'

import { auth } from '@/auth'
import { ThemeProvider } from '@/context/Theme'
import { Toaster } from '@/ui/shadcn/sonner'

const inter = localFont({
  src: './fonts/Inter.ttf',
  variable: '--font-inter',
  weight: '100 200 300 400 500 600 700 800 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({ children }: { children: ReactNode }) => {
  const session = await auth()

  return (
    <html lang='ru' suppressHydrationWarning>
      <SessionProvider session={session}>
        <body className={`${inter.className} antialiased`}>
          <ThemeProvider>{children}</ThemeProvider>
          <Toaster position='top-right' />
        </body>
      </SessionProvider>
    </html>
  )
}

export default RootLayout
